### PR TITLE
feat: improve commit count with author, date, and verification

### PR DESCRIPTION
**Pull request by maxneuvians**
This PR changes its from:

```
{
  metadata_owner: 'cds-snc',
  metadata_repo: 'github-repository-metadata-exporter',
  metadata_query: 'commit_count',
  metadata_time_in_days: 60,
  metadata_since: '2022-10-06T17:59:38.453Z',
  commit_count: 16
}
``` 

to: 

```
{
  metadata_owner: 'cds-snc',
  metadata_repo: 'github-repository-metadata-exporter',
  metadata_query: 'commit_count',
  metadata_time_in_days: 60,
  metadata_since: '2022-10-06T21:40:59.356Z',
  commit_count: [
    {
      author: 'maxneuvians',
      date: '2022-12-05T17:59:12Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'renovate[bot]',
      date: '2022-12-05T17:00:09Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'renovate[bot]',
      date: '2022-12-05T16:59:49Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'renovate[bot]',
      date: '2022-12-05T16:50:52Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'renovate[bot]',
      date: '2022-12-05T16:50:23Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'maxneuvians',
      date: '2022-12-05T16:49:47Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'renovate[bot]',
      date: '2022-12-02T21:38:35Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'maxneuvians',
      date: '2022-12-02T18:28:38Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'renovate[bot]',
      date: '2022-12-02T18:17:47Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'maxneuvians',
      date: '2022-12-02T17:17:01Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'maxneuvians',
      date: '2022-12-02T16:11:29Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'renovate[bot]',
      date: '2022-12-02T16:09:15Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'maxneuvians',
      date: '2022-12-02T15:27:03Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'maxneuvians',
      date: '2022-12-01T18:34:13Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'maxneuvians',
      date: '2022-12-01T14:48:29Z',
      verified: true,
      verified_reason: 'valid'
    },
    {
      author: 'maxneuvians',
      date: '2022-12-01T14:29:11Z',
      verified: true,
      verified_reason: 'valid'
    }
  ]
}
````

### CODE REVIEW

**Comment by CalvinRodo** [comment]
So this will return all commits to sentinel?

**Comment by maxneuvians** [comment]
Last 60 days

**Comment by CalvinRodo** [comment]
Okay, would it not make more sense to just check that this is enabled? 
image

**Comment by maxneuvians** [comment]
Some people don't want that on, but I would like to see how many are verified anyways

**Pull request merged**
